# 生产环境覆盖配置
services:
  # 数据库优化配置
  postgres:
    environment:
      POSTGRES_DB: insplan_production
      POSTGRES_USER: insplan_prod
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Redis 生产配置
  redis:
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_prod_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # API 网关生产配置
  api-gateway:
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - RATE_LIMIT=1000
      - ENVIRONMENT=production
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # 用户服务生产配置
  user-service:
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ENVIRONMENT=production
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # 计划服务生产配置
  plan-service:
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - ENVIRONMENT=production
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # 订单服务生产配置
  order-service:
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ENVIRONMENT=production
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # 支付服务生产配置
  payment-service:
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - ALIPAY_APP_ID=${ALIPAY_APP_ID}
      - ALIPAY_PRIVATE_KEY=${ALIPAY_PRIVATE_KEY}
      - WECHAT_APP_ID=${WECHAT_APP_ID}
      - WECHAT_MCH_ID=${WECHAT_MCH_ID}
      - WECHAT_KEY=${WECHAT_KEY}
      - ENVIRONMENT=production
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # 通知服务生产配置
  notification-service:
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMS_ACCESS_KEY_ID=${SMS_ACCESS_KEY_ID}
      - SMS_ACCESS_KEY_SECRET=${SMS_ACCESS_KEY_SECRET}
      - ENVIRONMENT=production
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api-gateway
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

volumes:
  postgres_prod_data:
  redis_prod_data:
