services:
  # 数据库服务
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: insplan_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - insplan-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - insplan-network

  # 服务注册与发现 - 使用具体版本
  consul:
    image: hashicorp/consul:1.15
    ports:
      - "8500:8500"
    command: ["consul", "agent", "-dev", "-client", "0.0.0.0"]
    networks:
      - insplan-network

  # API 网关
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your-secret-key
      - PORT=8080
    depends_on:
      - consul
    networks:
      - insplan-network

  # 用户服务
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=user_service_db
      - JWT_SECRET=your-secret-key
      - PORT=8081
      - SERVICE_HOST=user-service
      - SERVICE_PORT=8081
    depends_on:
      - postgres
      - consul
    networks:
      - insplan-network

volumes:
  postgres_data:

networks:
  insplan-network:
    driver: bridge
