global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Plan Service
  - job_name: 'plan-service'
    static_configs:
      - targets: ['plan-service:8082']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Order Service
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8083']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Payment Service
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8084']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Consul
  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']
